# Generated by Django 5.2.8 on 2025-12-01 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cat_type",
                    models.CharField(
                        choices=[("EVENT", "Event"), ("HUSTLE", "Hustle")],
                        max_length=10,
                    ),
                ),
                ("icon", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="events/")),
                ("date_time", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market_hub.category",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_identity.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HustleListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SOLD", "Sold"),
                            ("DRAFT", "Draft"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_updated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market_hub.category",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_identity.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="market_hub.hustlelisting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS", "Business"),
                            ("CLUB", "Club"),
                            ("SCHOOL", "School"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("logo", models.ImageField(upload_to="orgs_logos/")),
                ("name", models.CharField(max_length=255)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Format: +2547xxxxxxxxx. Buyers will click to chat",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_identity.university",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hustlelisting",
            name="Organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market_hub.organization",
            ),
        ),
        migrations.CreateModel(
            name="EventListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "media",
                    models.FileField(
                        blank=True, null=True, upload_to="event_listing_media/"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_hub.event",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_identity.university",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_hub.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="market_hub.organization",
            ),
        ),
    ]
