# Generated by Django 5.2.8 on 2025-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_hub", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hustlelisting",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="hustlelisting",
            old_name="Organization",
            new_name="organization",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="eventlisting",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="hustlelisting",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="orgs_logos/"),
        ),
    ]
