# Generated by Django 5.2.8 on 2025-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("user_hash", models.CharField(max_length=255)),
                ("user_tags", models.JSONField()),
                ("meta_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp", "event_type"],
                        name="data_engine_timesta_c8fda6_idx",
                    )
                ],
            },
        ),
    ]
