# Generated by Django 5.2.8 on 2025-12-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="email",
        ),
    ]
